site_name: Otávio Larrosa - otaviolarrosa.github.io
site_url: https://otaviolarrosa.github.io/blog
theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - content.code.copy
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
      media: "(prefers-color-scheme: dark)"
nav:
  - Início: index.md
  - Posts:
      - 2025:
          - 09:
              - Hello World: posts/2025/09/hello-world.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
