site_name: Otávio Larrosa - otaviolarrosa.github.io
site_url: https://otaviolarrosa.github.io/blog
extra:
  generator: false
theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - content.code.copy
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
      media: "(prefers-color-scheme: dark)"
nav:
  - Início: index.md
  - Posts:
    - 2025:
      - 09:
        - Hello World: posts/2025/09/hello-world.md
      - 10:
        - Scripts C#: posts/2025/10/scripts-csharp-dotnet10.md
    - 2026:
      - 04:
        - .NET 11 Preview 3: posts/2026/04/dotnet11-preview3.md
        - GitHub Copilot muda planos individuais: posts/2026/04/copilot-mudancas-planos.md
      - 05:
        - Token Savior + GitHub Copilot - Como Configurar o Servidor MCP: posts/2026/05/token-savior-copilot.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
